#!/usr/bin/env python

import sys

from rqt_mypkg.critical_time import CriticalTime
from rqt_gui.main import Main

plugin = 'critical_time'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
