#!/usr/bin/env python

import sys

from rqt_mypkg.short_topics import ShortTopic
from rqt_gui.main import Main

plugin = 'short_topics'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
